spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/pcbonline?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    druid:
      filters: stat,wall,slf4j,default
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #WebStatFilter用于采集web-jdbc关联监控的数据。
      #https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_%E9%85%8D%E7%BD%AEWebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #Druid内置提供了一个StatViewServlet用于展示Druid的统计信息。
      #https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
#        login-password: admin
#        login-username: 112233
      filter:
        stat:
          #慢sql记录
          log-slow-sql: true
          slow-sql-millis: 1000
          #sql合并设置
          merge-sql: false
        #墙
        wall:
          config:
            multi-statement-allow: true
        #使用slf4进行sql日志输出
        slf4j:
          enabled: true
          #所有Statement相关的日志
          statement-log-enabled: false
          statement-create-after-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: true


