server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    connection-timeout: 1000ms
  port: 8877
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/css,text/plain,application/json,application/xml,application/javascript

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB #限制文件的上传为100m
      max-request-size: 100MB
      enabled: true #开启文件上传
  #启用bean名称覆盖
  main:
    allow-bean-definition-overriding: true
  #email
  mail:
    host: smtp.qiye.aliyun.com #发送邮件服务器
    username: team@pcbonline.com #邮箱
    password: PCBONLINE2020@ #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
#    properties.mail.display.sendmail: Javen #可以任意
#    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8


#    from: 1170737711@qq.com #与上面的username保持一致

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jugu.www.pcbonlinev2.domain.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls:
#looger
logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint}|%clr(${LOG_LEVEL_PATTERN:%5p})|%clr(%X{traceId})|%clr(${PID}){magenta}|%clr(%15.15t){faint}|%clr(%-40.40logger{39}){cyan}%clr(:){faint} %m %n'
#  level:
#    druid:
#      sql:
#        Statement: debug

pcbonline:
  send-notice-base-url: http://localhost:3000
  registered-coupon-grant: true
  google-catcha-verify-switch: false
  common-pwd: PCBonline888
  img-access-url: http://localhost:8871/file
  img-upload-dir: /Users/mc/WorkProject/pcbonline/compressed
  merchant-id: 1557899299
  business-id: 1557899299001
  card-pay-url: https://test-gateway.ginltech.com/payment/interface/do
  sign-key: zZlNcuJyTtmEVRoh
